### ISSUE TITLE
Crash when crafting an item from another mod

### ISSUE THREAD

**Issue by wqferr** [DeflatedPickle/SmartHUDReheated#5]
This crash refers to when crafting a herbal medicine from Better Nether. All version information is provided below:

- Minecraft v1.18.1
- Better Nether v6.0.8
- SmartHUDReheated v3.2.0

I have a **guess** as to what is happening at the bottom of the post.

<details>
<summary>Relevant logs section</summary>
<pre>
java.lang.NullPointerException: null
	at com.deflatedpickle.smarthud.util.ItemStackKt.toStack(ItemStack.kt:17) ~[smarthud-3.2.0.jar:?]
	at com.deflatedpickle.smarthud.util.ListKt.toStackList(List.kt:10) ~[smarthud-3.2.0.jar:?]
	at com.deflatedpickle.smarthud.util.PlayerEntityKt.toPlayer(PlayerEntity.kt:13) ~[smarthud-3.2.0.jar:?]
	at com.deflatedpickle.smarthud.SmartHUDReheated.drawSection(SmartHUDReheated.kt:62) ~[smarthud-3.2.0.jar:?]
	at com.deflatedpickle.smarthud.SmartHUDReheated.drawSmartHUDBackground(SmartHUDReheated.kt:136) ~[smarthud-3.2.0.jar:?]
	at net.minecraft.class_329.handler$dgl000$drawSmartHUDBackground(class_329.java:8024) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1759(class_329.java:581) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[01:52:15] [Render thread/INFO]: Stopping worker threads
</pre>
</details>

This crash first happened when I crafted the item itself. I sadly cant remember if it was just as I clicked the crafting output or if I had the time to put it in my inventory. The same crash happened when reloading the world.  I had a ton of other mods installed at the same time. The stack trace suggests this one is the main culprit, and disabling it let me log back onto the server.

**I believe the HUD is trying to read a property that the Better Nether item neglected or explicitly set to null, which is causing the main thread to panic.** Hopefully that's the case, since the fix would probably be quite simple.

Thanks in advance! If you need more information or testing, I'd be happy to help.

**Comment by Rafii2198** [comment]
Similar thing happens when I crafted Oak Post from Adorn mod.
[Here on Crashy](https://crashy.net/UNeONLbtbAcgGkvYCnyM) is my crash report, maybe it will be useful too.

It crashed when I tried to put in my inventory itself, when I clicked on it in crafting table everything was fine until I put it in my inventory.
