### ISSUE TITLE
Incompatible with 1.18.2

### ISSUE THREAD

**Issue by ActualBest** [DeflatedPickle/SmartHUDReheated#9]
When I tried to launch Fabric with this mod, I was told that it is not compatible with 1.18.2

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'SmartHUDReheated' (smarthud) 3.2.0 with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'SmartHUDReheated' (smarthud) 3.2.0 requires version 1.18.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by U5B** [comment]
Changing the required version from 1.18.1 to 1.18.2 in fabric.mod.json located inside the mod should be enough for this mod to load on 1.18.2.

The line to change should look like this: https://github.com/DeflatedPickle/SmartHUDReheated/blob/main/src/main/resources/fabric.mod.json#L34

**Comment by ActualBest** [comment]
Also incompatible with 1.19
